from api.admin.getUsersByStat import getUsersByStat
from api.admin.createAnnouncement import createAnnouncement
from api.admin.createDepartment import createDepartment
from api.admin.loadAnnouncements import loadAnnouncements
from api.admin.deleteAnnouncement import deleteAnnouncement
from api.admin.updateAnnouncement import updateAnnouncement
from api.admin.listAllEmployees import listAllEmployees
from api.admin.listAllVendors import listAllVendors
from api.admin.listAllDepartments import listAllDepartments
from api.admin.deleteDepartment import deleteDepartment
from api.admin.renameDepartment import renameDepartment
from api.admin.loadDepartment import loadDepartment
from api.admin.loadDepartmentEmployees import loadDepartmentEmployees
from api.admin.loadVendor import loadVendor
from api.admin.loadVendorComplaints import loadVendorComplaints
from api.admin.changeVendorDepartment import changeVendorDepartment
from api.admin.deleteVendor import deleteVendor
from api.admin.toggleVendorAccountActivation import toggleVendorAccountActivation
from api.admin.loadEmployee import loadEmployee
from api.admin.loadEmployeeComplaints import loadEmployeeComplaints
from api.admin.changeEmployeeRoomNo import changeEmployeeRoomNo
from api.admin.deleteEmployee import deleteEmployee
from api.admin.toggleEmployeeAccountActivation import toggleEmployeeAccountActivation
from api.admin.listAllComplaints import listAllComplaints
from api.admin.createNewUser import createNewUser
from api.admin.fetchDetails import fetchDetails
from api.admin.deleteAccount import deleteAccount
from api.admin.saveSettings import saveSettings
from api.admin.searchDepartment import searchDepartment
from api.admin.searchEmployee import searchEmployee
from api.admin.searchVendor import searchVendor
from api.admin.searchComplaint import searchComplaint
from api.admin.viewComplaint import viewComplaint
